name: worktracker
description: "WorkTracker: A simple and professional work activity tracker for teams."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  injectable: ^2.5.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.2
  connectivity_plus: ^6.1.4
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  formz: ^0.8.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  go_router: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
  fonts:
    - family: TT Interphases
      fonts:
        - asset: assets/fonts/InterphasesProThin.ttf
          weight: 100
        - asset: assets/fonts/InterphasesProExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterphasesProLight.ttf
          weight: 300
        - asset: assets/fonts/InterphasesProRegular.ttf
          weight: 400
        - asset: assets/fonts/InterphasesProMedium.ttf
          weight: 500
        - asset: assets/fonts/InterphasesProDemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterphasesProBold.ttf
          weight: 700
        - asset: assets/fonts/InterphasesProExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterphasesProBlack.ttf
          weight: 900
