name: worktracker
description: "WorkTracker: A simple and professional work activity tracker for teams."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  logger: ^2.5.0
  flutter_svg: ^2.1.0
  firebase_storage: ^12.4.7
  firebase_remote_config: ^5.4.5
  meta: ^1.15.0
  go_router: ^15.1.2
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    # - assets/icons/
    # - assets/logos/
    - assets/fonts/
  fonts:
    - family: TT Interphases
      fonts:
        - asset: assets/fonts/InterphasesProThin.ttf
          weight: 100
        - asset: assets/fonts/InterphasesProExtraLight.ttf
          weight: 200
        - asset: assets/fonts/InterphasesProLight.ttf
          weight: 300
        - asset: assets/fonts/InterphasesProRegular.ttf
          weight: 400
        - asset: assets/fonts/InterphasesProMedium.ttf
          weight: 500
        - asset: assets/fonts/InterphasesProDemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterphasesProBold.ttf
          weight: 700
        - asset: assets/fonts/InterphasesProExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterphasesProBlack.ttf
          weight: 900
